### PR TITLE
Add Version Checking for Local Dependencies

### PR DESCRIPTION
**Pull request by PercentBoat4164**
- [x] Add version checking for local dependencies

This will allow us to reject package versions that will not work, or are not verified to work with our system.

### CODE REVIEW

**Comment by PercentBoat4164** [comment]
@JoelLogan, if you could take a chance to look at this and give me feedback on it that would be great. I edited the code to be more understandable, added proper version checking for local dependencies, added the option to specify acceptable versions of each dependency, and finally I started work on breaking up the code. Rather than having the code work with all types of dependencies (i.e. GitHub tags, URLs, and locally installed packages), I started separating those parts of the code to make it cleaner, easier to understand and more flexible to work with the nuisances of how each fetching and version control mechanism works. If you have any comments, thoughts or features you would like to see me add, please let me know.

**Review by JoelLogan — CHANGES_REQUESTED** [review]
I really like how it looks and the concept is much better.

However, I'm having an error when loading the CMake project.

```
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=ninja -DCMAKE_C_COMPILER=/usr/bin/gcc-11 -DCMAKE_CXX_COMPILER=/usr/bin/g++-11 -G Ninja -S IlluminationEngine/Illumination-Engine -B IlluminationEngine/Illumination-Engine/cmake-build-debug
-- Using remote assimp version v5.2.5.
CMake Error at /usr/lib/cmake/glm/glmConfig-version.cmake:2 (if):
  if given arguments:

    "0.0" "VERSION_LESS"

  Unknown arguments specified
Call Stack (most recent call first):
  ext/CMakeLists.txt:156 (find_package)
  ext/CMakeLists.txt:218 (FindLocalLib)

```

**Comment by PercentBoat4164** [comment]
So, after some internet searching it looks like this is a problem on their side. I don't think there is much that I can do to fix it apart from submitting a pull request fixing the issue. I don't think that I will do that however because I don't know where to begin. I looked in their files and could not find where the problem was, though I do understand what the problem is (I think). As there is no option to open issues on GLM's GitHub page, I don't think I will do anything. I have implemented a work around for this problem in our code though. I added a simple switch that allows one to completely bypass the local dependency searching phase and skip to the remote download phase. This worked in my Linux testing environment. I realize that it is a sub-optimal solution, but I don't see a better one for the time being. The only option that I can see to improve this would be to get them to fix their stuff. If you really want a good solution for this, I suggest opening a pull request in their repository with a clear description of the error and see if they respond. Do you have any thoughts on this solution?

**Review by JoelLogan — APPROVED** [review]
It builds and works correctly.

**Pull request merged**
